site_name: LangChain.Providers .NET Documentation
site_description: Documentation for the tryAGI .NET SDK for LangChain.Providers.
site_url: https://tryagi.github.io/LangChain.Providers/
repo_url: https://github.com/tryAGI/LangChain.Providers
repo_name: tryAGI/LangChain.Providers
edit_uri: edit/main/docs/
nav:
- Overview: index.md

theme:
  name: tryagi
  favicon: 'media/icon128.png'

plugins:
  - search
  - copy-to-llm

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
