name: Auto-approve and auto-merge bot pull requests
on:
  workflow_run:
    workflows:
      - Build and test
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    uses: tryAGI/workflows/.github/workflows/auto-merge.yml@main
    secrets: inherit
